-- Preferenze notifiche push per ogni utente
-- Master: M1-M6, Utenti base: U1-U9
-- Tutti i default a TRUE: tutte le notifiche attive per i nuovi utenti

ALTER TABLE profiles ADD COLUMN notif_m1 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_m2 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_m3 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_m4 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_m5 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_m6 BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE profiles ADD COLUMN notif_u1 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_u2 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_u3 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_u4 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_u5 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_u6 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_u7 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_u8 BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE profiles ADD COLUMN notif_u9 BOOLEAN NOT NULL DEFAULT TRUE;
